export const states = [
    { name: "Alabama", abbrevation: "AL" },
    { name: "Alaska", abbrevation: "AK" },
    { name: "Arizona", abbrevation: "AZ" },
    { name: "Arkansas", abbrevation: "AR" },
    { name: "California", abbrevation: "CA" },
    { name: "Colorado", abbrevation: "CO" },
    { name: "Connecticut", abbrevation: "CT" },
    { name: "Delaware", abbrevation: "DE" },
    { name: "Florida", abbrevation: "FL" },
    { name: "Georgia", abbrevation: "GA" },
    { name: "Hawaii", abbrevation: "HI" },
    { name: "Idaho", abbrevation: "ID" },
    { name: "Illinois", abbrevation: "IL" },
    { name: "Indiana", abbrevation: "IN" },
    { name: "Iowa", abbrevation: "IA" },
    { name: "Kansas", abbrevation: "KS" },
    { name: "Kentucky[E]", abbrevation: "KY" },
    { name: "Louisiana", abbrevation: "LA" },
    { name: "Maine", abbrevation: "ME" },
    { name: "Maryland", abbrevation: "MD" },
    { name: "Massachusetts[F]", abbrevation: "MA" },
    { name: "Michigan", abbrevation: "MI" },
    { name: "Minnesota", abbrevation: "MN" },
    { name: "Mississippi", abbrevation: "MS" },
    { name: "Missouri", abbrevation: "MO" },
    { name: "Montana", abbrevation: "MT" },
    { name: "Nebraska", abbrevation: "NE" },
    { name: "Nevada", abbrevation: "NV" },
    { name: "New Hampshire", abbrevation: "NH" },
    { name: "New Jersey", abbrevation: "NJ" },
    { name: "New Mexico", abbrevation: "NM" },
    { name: "New York", abbrevation: "NY" },
    { name: "North Carolina", abbrevation: "NC" },
    { name: "North Dakota", abbrevation: "ND" },
    { name: "Ohio", abbrevation: "OH" },
    { name: "Oklahoma", abbrevation: "OK" },
    { name: "Oregon", abbrevation: "OR" },
    { name: "Pennsylvania[G]", abbrevation: "PA" },
    { name: "Rhode Island[H]", abbrevation: "RI" },
    { name: "South Carolina", abbrevation: "SC" },
    { name: "South Dakota", abbrevation: "SD" },
    { name: "Tennessee", abbrevation: "TN" },
    { name: "Texas", abbrevation: "TX" },
    { name: "Utah", abbrevation: "UT" },
    { name: "Vermont", abbrevation: "VT" },
    { name: "Virginia[I]", abbrevation: "VA" },
    { name: "Washington", abbrevation: "WA" },
    { name: "West Virginia", abbrevation: "WV" },
    { name: "Wisconsin", abbrevation: "WI" },
    { name: "Wyoming", abbrevation: "WY" }
];
